module EmailBlacklist
  
  def blacklisted_email?(email)
    return false if email.blank?
    user, domain = email.split("@")
    email_blacklist.include?(domain)
  end
  
  def email_blacklist
    @email_blacklist ||= [ 'kaxy.com',
    'mail2world.com',
    'hotmail.com',
    'gmail.google.com',
    'gmail.com',
    'yahoo.com',
    'mail.yahoo.com',
    'mail.com',
    'webmail.aol.com',
    'aol.com',
    'mail2web.com',
    'mailinator.com',
    'fastmail.fm',
    'mail.lycos.com',
    'netaddress.com',
    'walla.com',
    'postmaster.co.uk',
    'zzn.com',
    'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com',
    '10minutemail.com',
    'pookmail.com',
    'dodgeit.com',
    'doramail.com',
    'xasamail.com',
    'mail.excite.com',
    'excite.com',
    'myrealbox.com',
    'mail2world.com',
    'hushmail.com',
    'e-mailanywhere.com',
    'flashmail.com',
    'caramail.lycos.fr',
    'webmail.juno.com',
    'juno.com',
    'webmail.earthlink.net',
    'earthlink.com',
    'nameplanet.com',
    'icqmail.com',
    'mailandnews.com',
    'orgoo.com',
    'aventuremail.com',
    'postmaster.info.aol.com',
    'prontomail.com',
    'fuzzmail.org',
    'mail.indiatimes.com',
    'indiatimes.com',
    'gurlmail.com',
    'mauimail.com',
    'eo.yifan.net',
    'thedoghousemail.com',
    'emailaccount.com',
    'returnreceipt.com',
    'personal.ro',
    'meowmail.com',
    'wongfaye.com',
    'computermail.net',
    'mypersonalemail.com',
    'everymail.com',
    'kaxy.com',
    'muchomail.com',
    'byke.com',
    'kukamail.com',
    'katchup.co.nz',
    'probemail.com',
    'godmail.com',
    '123vn.com',
    'rediff.com',
    'howlermonkey.net',
    'jershie.zzn.com',
    'witchesbrew.zzn.com',
    'bachelorgirl.zzn.com',
    'zapak.com/zapakmail.z',
    'zapak.com',
    'email.iwon.com',
    'iwon.com',
    'web.synacor.com',
    'aaemail.com',
    'phat.co.nz',
    'stoolmail.zzn.com',
    'zzn.com',
    'expatmail.net',
    'nz11.com',
    'epenguin.zzn.com',
    'galacmail.com',
    'merawalaemail.com',
    'mikellmail.zzn.com',
    'popmail.walkerware.ca',
    'mail.zappo.com',
    'zappo.com',
    'atgratis.com/index.asp' ]
  end

end