class EditDefaultBadges < ActiveRecord::Migration
  def up
    if false && Badge.count > 0
        Badge.where(name: 'boss').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'caring').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'coffee_maker').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'comedian').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'cooperative').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'detailed').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'efficient').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'friend').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'fun').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'honorable').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'innovative').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'leader').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'listener').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'on_track').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'organized').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'passionate').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'peace_maker').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'powerful').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'problem_solver').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'provider').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'punctual').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'responsive').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'speaker').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'speedy').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'new_user').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'on_fire').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'hacker').first.update_attribute(:disabled_at, Time.now)
        Badge.where(name: 'ambassador').first.update_attribute(:disabled_at, Time.now)
    end
  end

  def down
    Badge.where(name: 'boss').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'caring').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'coffee_maker').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'comedian').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'cooperative').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'detailed').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'efficient').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'friend').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'fun').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'honorable').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'innovative').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'leader').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'listener').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'on_track').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'organized').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'passionate').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'peace_maker').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'powerful').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'problem_solver').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'provider').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'punctual').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'responsive').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'speaker').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'speedy').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'new_user').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'on_fire').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'hacker').first.update_attribute(:disabled_at, nil)
    Badge.where(name: 'ambassador').first.update_attribute(:disabled_at, nil)
  end
end
